from .user_home import *
from .authentication import *
from .user_view import *
from .location_view import *
from .staffs import *
from .subjects import *
from .terms import *
from .levels import *
from .topics import *
from .academic_year import *
from .academic_term import *
from .teaching_calendar import *
from .excel_views import *
from .workload import *
from .teacher_workload import *
from .teaching_report import *