# Generated by Django 4.1.7 on 2023-04-10 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_school_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_week', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Year',
                'db_table': 'academic_year',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Level',
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TeachingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_tc', to='curriculum.academicyear')),
            ],
            options={
                'verbose_name': 'Teaching Calendar',
                'verbose_name_plural': 'Teaching Calendar',
                'db_table': 'teaching_calendar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('max_week', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_level', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_subject', to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='TeachingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tc', to='curriculum.teachingcalendar')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_teacher', to='curriculum.staff')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_verifier', to='curriculum.staff')),
            ],
            options={
                'verbose_name': 'Teaching Report',
                'verbose_name_plural': 'Teaching Report',
                'db_table': 'teaching_report',
            },
        ),
        migrations.AddField(
            model_name='teachingcalendar',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tc', to='curriculum.topic'),
        ),
    ]
