# Generated by Django 4.1.7 on 2023-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_term_remove_academicyear_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='total_week',
            field=models.IntegerField(null=True),
        ),
    ]
