# Generated by Django 4.1.7 on 2023-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_academicyear_total_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='total_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
