# Generated by Django 4.1.7 on 2023-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_academicyear_total_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='total_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
