# Generated by Django 4.1.7 on 2023-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_level_name_alter_subject_name_alter_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
