# Generated by Django 4.1.7 on 2023-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_topic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.IntegerField(unique=True),
        ),
    ]
