# Generated by Django 4.1.7 on 2023-04-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_alter_academicyear_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('academic_year', 'term')},
        ),
    ]
