# Generated by Django 4.1.7 on 2023-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_alter_academicterm_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingcalendar',
            name='total_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
