# Generated by Django 4.1.7 on 2023-04-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_teachingcalendar_total_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingcalendar',
            unique_together={('topic', 'academic_term')},
        ),
    ]
