# Generated by Django 4.1.7 on 2023-06-08 15:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_academicyear_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingreport',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teachingreport',
            name='report',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teachingreport',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_verifier', to='curriculum.staff'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='one_current_academic_year'),
        ),
    ]
