# Generated by Django 4.1.7 on 2023-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_alter_teachingreport_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingreport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
