# Generated by Django 4.1.7 on 2023-06-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_remove_teachingreport_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingProgressSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_progress_year', to='curriculum.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shool_level_progress', to='curriculum.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_progress', to='curriculum.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'Teaching Progress_summary',
                'verbose_name_plural': 'Teaching Calendar',
                'db_table': 'teaching_progress_summary',
                'unique_together': {('subject', 'level', 'school', 'academic_year')},
            },
        ),
    ]
