# Generated by Django 4.1.7 on 2023-06-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_teachingprogresssummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingprogresssummary',
            options={'verbose_name': 'Teaching Progress_summary', 'verbose_name_plural': 'Teaching Progress Summary'},
        ),
        migrations.CreateModel(
            name='TeachingLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.CharField(max_length=100)),
                ('concept_covered', models.CharField(max_length=100)),
                ('Workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_workload', to='curriculum.workload')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_topic', to='curriculum.topic')),
            ],
            options={
                'verbose_name': 'Logbook',
                'verbose_name_plural': 'Logbook',
                'db_table': 'Logbook',
            },
        ),
    ]
