# Generated by Django 4.1.7 on 2023-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_alter_teachingprogresssummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinglogbook',
            name='evidence',
            field=models.ImageField(default=1, unique=True, upload_to='evidence'),
            preserve_default=False,
        ),
    ]
