# Generated by Django 4.1.7 on 2023-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0023_teachinglogbook_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinglogbook',
            name='concept_covered',
            field=models.TextField(),
        ),
    ]
